# Generated by Django 4.0.6 on 2022-08-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_station', models.CharField(max_length=100)),
                ('yield_year', models.IntegerField()),
                ('avg_max_temp', models.FloatField(null=True)),
                ('avg_min_temp', models.FloatField(null=True)),
                ('total_precipitation', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_station', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
                ('max_temp', models.IntegerField(null=True)),
                ('min_temp', models.IntegerField(null=True)),
                ('precipitation', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'weatherdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_year', models.IntegerField()),
                ('total_yield', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'yielddata',
                'managed': False,
            },
        ),
    ]
